#!/usr/bin/env python3
"""Filter inline assembly blocks from CSV files.

Removes PTX assembly blocks that start with:
    //
    // Generated by LLVM NVPTX Back-End
    //
and end with:
    .section        .debug_macinfo  {       }

The file is overwritten in place.
"""

import argparse
import re


def filter_inline_assembly(content: str) -> str:
    # Match assembly blocks: starts with the LLVM NVPTX header,
    # ends with .debug_macinfo section
    pattern = re.compile(
        r"//\s*\n//\s*Generated by LLVM NVPTX Back-End\s*\n//.*?"
        r"\.section\s+\.debug_macinfo\s*\{[^}]*\}",
        re.DOTALL,
    )
    return pattern.sub("", content)


def main():
    parser = argparse.ArgumentParser(
        description="Filter inline assembly from CSV files"
    )
    parser.add_argument("file", help="Path to the CSV file to filter")
    args = parser.parse_args()

    with open(args.file, "r") as f:
        content = f.read()

    original_len = len(content)
    filtered = filter_inline_assembly(content)
    removed_len = original_len - len(filtered)

    with open(args.file, "w") as f:
        f.write(filtered)

    print(f"Filtered {removed_len} characters of inline assembly from {args.file}")


if __name__ == "__main__":
    main()
